/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace TicTacToeChallenge.Lib.DataClasses
{                   
    
    public partial class AirtableAttachment 
    {
        public AirtableAttachment()
        {
            this.InitPoco();
        }
                            
    }
}