/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - An odxml42 Tool
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;

namespace TicTacToeChallenge.Lib.DataClasses
{

    public partial class Cell
    {
        public Cell()
        {
            this.InitPoco();
        }

        public static Cell None { get { return null; } }

        public string GetDisplayName()
        {
            return String.Format("{0}. {1} - {2}", this.CellKey, this.Name, this.CurrentState);
        }

        public override String ToString()
        {
            return String.Format("{0}. {1} - {2}", this.CellKey, this.Name, this.CurrentState);
        }

    }
}